/**
 * Datafeed JS API for TradingView Advanced Charts
 * @packageDocumentation
 * @module Datafeed
 */
// Generated by dts-bundle-generator v9.5.1

/**
 * This is the generic type useful for declaring a nominal type,
 * which does not structurally matches with the base type and
 * the other types declared over the same base type
 *
 * Usage:
 * @example
 * type Index = Nominal<number, 'Index'>;
 * // let i: Index = 42; // this fails to compile
 * let i: Index = 42 as Index; // OK
 * @example
 * type TagName = Nominal<string, 'TagName'>;
 */
export declare type Nominal<T, Name extends string> = T & { /* eslint-disable-next-line jsdoc/require-jsdoc */
	[Symbol.species]: Name;
};
/**
 * Bar data point
 */
export interface Bar {
	/** Bar time.
	 * Amount of **milliseconds** since Unix epoch start in **UTC** timezone.
	 * `time` for daily, weekly, and monthly bars is expected to be a trading day (not session start day) at 00:00 UTC.
	 * The library adjusts time according to `session` from {@link LibrarySymbolInfo}.
	 */
	time: number;
	/** Opening price */
	open: number;
	/** High price */
	high: number;
	/** Low price */
	low: number;
	/** Closing price */
	close: number;
	/** Trading Volume */
	volume?: number;
}
export interface CurrencyItem {
	/** Unique ID */
	id: string;
	/** Currency code. @example `USD` */
	code: string;
	/** URL to an image of the currency. SVG logos are preferable, but please make sure that the provided image fits nicely in the currency select control (for raster images the expected size is 24x24px). */
	logoUrl?: string;
	/** Description for the currency */
	description?: string;
}
/**
 * Depth of Market (Order Book) Data
 */
export interface DOMData {
	/**
	 * Whether the Depth of Market data is a snapshot (has the full set of depth data).
	 * - If `true` then the data contains the full set of depth data.
	 * - If `false` then data only contains updated levels.
	 */
	snapshot: boolean;
	/** Ask order levels (must be sorted by `price` in ascending order) */
	asks: DOMLevel[];
	/** Bid order levels (must be sorted by `price` in ascending order) */
	bids: DOMLevel[];
}
/**
 * Depth of Market Level
 */
export interface DOMLevel {
	/** Price for DOM level */
	price: number;
	/** Volume for DOM level */
	volume: number;
}
/**
 * Datafeed configuration data.
 * Pass the resulting array of properties as a parameter to {@link OnReadyCallback} of the [`onReady`](https://www.tradingview.com/charting-library-docs/latest/connecting_data/datafeed-api/required-methods#onready) method.
 */
export interface DatafeedConfiguration {
	/**
	 * List of exchange descriptors.
	 * An empty array leads to an absence of the exchanges filter in the Symbol Search list.
	 * Use `value=''` if you wish to include all exchanges.
	 */
	exchanges?: Exchange[];
	/**
	 * List of [resolutions](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution) that the chart should support.
	 * Each item of the array is expected to be a string that has a specific [format](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution#resolution-format).
	 * If you set this property to `undefined` or an empty array, the _Resolution_ drop-down menu displays the list of resolutions available for
	 * the current symbol ({@link LibrarySymbolInfo.supported_resolutions}).
	 *
	 * @example
	 * `["1", "15", "240", "D", "6M"]` will give you "1 minute, 15 minutes, 4 hours, 1 day, 6 months" in the _Resolution_ drop-down menu.
	 */
	supported_resolutions?: ResolutionString[];
	/**
	 * Supported unit groups. Each group can have several unit objects.
	 *
	 * @example
	 * ```javascript
	 * {
	 *     weight: [
	 *         { id: 'kg', name: 'kg', description: 'Kilograms' },
	 *         { id: 'lb', name: 'lb', description: 'Pounds'},
	 *     ]
	 * }
	 * ```
	 */
	units?: Record<string, Unit[]>;
	/**
	 * Supported currencies for currency conversion.
	 *
	 * When a currency code is supplied as a string then the library will automatically convert it to `{ id: value, code: value }` object.
	 *
	 * @example `["USD", "EUR", "GBP"]`
	 * @example `[{ id: "USD", code: "USD", description: "$" }, { id: "EUR", code: "EUR", description: "€" }]`
	 */
	currency_codes?: (string | CurrencyItem)[];
	/** Does the datafeed supports marks on bars (`true`), or not (`false | undefined`). */
	supports_marks?: boolean;
	/** Set this one to `true` if your datafeed provides server time (unix time). It is used to adjust Countdown on the Price scale. */
	supports_time?: boolean;
	/** Does the datafeed supports marks on the timescale (`true`), or not (`false | undefined`). */
	supports_timescale_marks?: boolean;
	/**
	 * List of filter descriptors.
	 *
	 * Setting this property to `undefined` or an empty array leads to the absence of filter types in Symbol Search list. Use `value = ''` if you wish to include all filter types.
	 * `value` within the descriptor will be passed as `symbolType` argument to {@link IDatafeedChartApi.searchSymbols}
	 */
	symbols_types?: DatafeedSymbolType[];
	/**
	 * Set it if you want to group symbols in the [Symbol Search](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Symbol-Search).
	 * Represents an object where keys are symbol types {@link SymbolType} and values are regular expressions (each regular expression should divide an instrument name into 2 parts: a root and an expiration).
	 *
	 * Sample:
	 * ```
	 * {
	 *   "futures": `/^(.+)([12]!|[FGHJKMNQUVXZ]\d{1,2})$/`,
	 *   "stock": `/^(.+)([12]!|[FGHJKMNQUVXZ]\d{1,2})$/`,
	 * }
	 * ```
	 * It will be applied to the instruments with futures and stock as a type.
	 * Refer to [Symbol grouping](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Symbol-Search#symbol-grouping) for more information.
	 */
	symbols_grouping?: Record<string, string>;
}
/**
 * This object contains symbol quote values, where a quote represents a set of data describing the current price.
 * The library uses quote data for various trading functionalities, including the [Order Ticket](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/order-ticket), [Legend](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Legend),
 * and widgets, such as [Watchlist](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/Watch-List), [Details](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/#details),
 * [News](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/news), and [Depth of Market](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/#depth-of-market).
 *
 * While all properties in this object are marked as optional, populating most of them is required for supporting trading functionalities.
 * See property descriptions for more information.
 */
export interface DatafeedQuoteValues {
	/**
	 * Price change (usually counts as an open price on a particular day).
	 * Required for mobile apps. Otherwise, `NaN` values will appear in the [Legend](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Legend).
	 */
	ch?: number;
	/**
	 * Price change percentage.
	 * Required for mobile apps. Otherwise, `NaN` values will appear in the [Legend](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Legend).
	 */
	chp?: number;
	/** Short name for a symbol. Short name is used in the title for the [News](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/news), [Watchlist](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/Watch-List) and [Details](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/#details) widgets. You can disable the [`prefer_quote_short_name`](https://www.tradingview.com/charting-library-docs/latest/customization/Featuresets#prefer_quote_short_name) to use the {@link LibrarySymbolInfo.ticker} value instead. */
	short_name?: string;
	/** The name of the exchange */
	exchange?: string;
	/** A short description of the symbol. This description is displayed in the [Details](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/#details) widget and the tooltip of the [Watchlist](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/Watch-List) widget. */
	description?: string;
	/**
	 * The price at which the most recent trade of a security occurred, regardless of whether it was a buy or sell.
	 * Required for the [Details](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/#details) and [Watchlist](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/Watch-List) widgets.
	 */
	lp?: number;
	/** Ask price */
	ask?: number;
	/** Bid price */
	bid?: number;
	/** Spread (difference between the ask and bid prices) */
	spread?: number;
	/** Today's opening price */
	open_price?: number;
	/** Today's high price */
	high_price?: number;
	/** Today's low price */
	low_price?: number;
	/**
	 * Closing price of the symbol from the previous regular market session.
	 *
	 * Required for mobile apps. Otherwise, `NaN` values will appear in the [Legend](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Legend).
	 */
	prev_close_price?: number;
	/** Today's trading volume */
	volume?: number;
	/** Original name */
	original_name?: string;
	[valueName: string]: string | number | string[] | number[] | undefined;
}
export interface DatafeedSymbolType {
	/** Name of the symbol type */
	name: string;
	/** Value to be passed as the `symbolType` argument to `searchSymbols` */
	value: string;
}
/** Exchange Description */
export interface Exchange {
	/** Value to be passed as the `exchange` argument to `searchSymbols` */
	value: string;
	/** Name of the exchange */
	name: string;
	/** Description of the exchange */
	desc: string;
}
/**
 * Information passed to `onHistoryCallback` for getBars.
 */
export interface HistoryMetadata {
	/**
	 * Optional value indicating to the library that there is no more data on the server.
	 */
	noData?: boolean;
	/**
	 * The time of the next available bar in history. The time value should be represented with a Unix timestamp in milliseconds.
	 *
	 * You can pass the `nextTime` value to the library if there is no data in the time range that the library requests.
	 * Therefore, you notify the library about available data before the requested range and ensure that the next data request is for the right range.
	 * For more information, refer to the [How nextTime works](https://www.tradingview.com/charting-library-docs/latest/connecting_data/UDF#how-nexttime-works) section.
	 */
	nextTime?: number | null;
}
export interface IDatafeedChartApi {
	/**
	 * The library calls this function to get marks for visible bars range.
	 * The library assumes that you will call `onDataCallback` only once per `getMarks` call.
	 *
	 * A few marks per bar are allowed (for now, the maximum is 10). The time of each mark must match the time of a bar. For example, if the bar times are `2023-01-01`, `2023-01-08`, and `2023-01-15`, then a mark cannot have the time `2023-01-05`.
	 *
	 * **Remark:** This function will be called only if you confirmed that your back-end is supporting marks ({@link DatafeedConfiguration.supports_marks}).
	 *
	 * @param symbolInfo A SymbolInfo object
	 * @param from Unix timestamp (leftmost visible bar)
	 * @param to Unix timestamp (rightmost visible bar)
	 * @param onDataCallback Callback function containing an array of marks
	 * @param resolution Resolution of the symbol
	 */
	getMarks?(symbolInfo: LibrarySymbolInfo, from: number, to: number, onDataCallback: GetMarksCallback<Mark>, resolution: ResolutionString): void;
	/**
	 * The library calls this function to get timescale marks for visible bars range.
	 * The library assumes that you will call `onDataCallback` only once per `getTimescaleMarks` call.
	 *
	 * **Remark:** This function will be called only if you confirmed that your back-end is supporting marks ({@link DatafeedConfiguration.supports_timescale_marks}).
	 *
	 * @param symbolInfo A SymbolInfo object
	 * @param from Unix timestamp (leftmost visible bar)
	 * @param to Unix timestamp (rightmost visible bar)
	 * @param onDataCallback Callback function containing an array of marks
	 * @param resolution Resolution of the symbol
	 */
	getTimescaleMarks?(symbolInfo: LibrarySymbolInfo, from: number, to: number, onDataCallback: GetMarksCallback<TimescaleMark>, resolution: ResolutionString): void;
	/**
	 * This function is called if the `supports_time` configuration flag is `true` when the chart needs to know the server time.
	 * The library expects a callback to be called once.
	 * The time is provided without milliseconds. Example: `1445324591`.
	 *
	 * `getServerTime` is used to display countdown on the price scale.
	 * Note that the countdown can be displayed only for [intraday](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution#resolution-in-minutes-intraday) resolutions.
	 */
	getServerTime?(callback: ServerTimeCallback): void;
	/**
	 * Provides a list of symbols that match the user's search query.
	 *
	 * @param userInput Text entered by user in the symbol search field
	 * @param exchange The requested exchange. Empty value means no filter was specified
	 * @param symbolType Type of symbol. Empty value means no filter was specified
	 * @param onResult Callback function that returns an array of results ({@link SearchSymbolResultItem}) or empty array if no symbols found
	 */
	searchSymbols(userInput: string, exchange: string, symbolType: string, onResult: SearchSymbolsCallback): void;
	/**
	 * The library will call this function when it needs to get SymbolInfo by symbol name.
	 *
	 * @param symbolName Symbol name or `ticker`
	 * @param onResolve Callback function returning a SymbolInfo ({@link LibrarySymbolInfo})
	 * @param onError Callback function whose only argument is a text error message
	 * @param extension An optional object with additional parameters
	 */
	resolveSymbol(symbolName: string, onResolve: ResolveCallback, onError: DatafeedErrorCallback, extension?: SymbolResolveExtension): void;
	/**
	 * This function is called when the chart needs a history fragment defined by dates range.
	 *
	 * @param symbolInfo A SymbolInfo object
	 * @param resolution Resolution of the symbol
	 * @param periodParams An object used to pass specific requirements for getting bars
	 * @param onResult Callback function for historical data
	 * @param onError Callback function whose only argument is a text error message
	 */
	getBars(symbolInfo: LibrarySymbolInfo, resolution: ResolutionString, periodParams: PeriodParams, onResult: HistoryCallback, onError: DatafeedErrorCallback): void;
	/**
	 * The library calls this function when it wants to receive real-time updates for a symbol.
	 * The library assumes that you will call the callback provided by the `onTick` parameter every time you want to update the most recent bar or to add a new one.
	 *
	 * @param symbolInfo A SymbolInfo object
	 * @param resolution Resolution of the symbol
	 * @param onTick Callback function returning a Bar object
	 * @param listenerGuid
	 * @param onResetCacheNeededCallback Function to be executed when bar data has changed
	 */
	subscribeBars(symbolInfo: LibrarySymbolInfo, resolution: ResolutionString, onTick: SubscribeBarsCallback, listenerGuid: string, onResetCacheNeededCallback: () => void): void;
	/**
	 * The library calls this function when it doesn't want to receive updates anymore.
	 *
	 * @param listenerGuid id to unsubscribe from
	 */
	unsubscribeBars(listenerGuid: string): void;
	/**
	 * The library calls this function when it wants to receive real-time symbol data in the [Depth of Market](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/depth-of-market) (DOM) widget.
	 * Note that you should set the {@link BrokerConfigFlags.supportLevel2Data} configuration flag to `true`.
	 *
	 * @param symbol A SymbolInfo object
	 * @param callback A function returning an object to update DOM data
	 * @returns A unique identifier that will be used to unsubscribe from the data
	 */
	subscribeDepth?(symbol: string, callback: DOMCallback): string;
	/**
	 * The library calls this function to stop receiving real-time updates for the [Depth of Market](https://www.tradingview.com/charting-library-docs/latest/trading_terminal/depth-of-market) listener.
	 * Note that you should set the {@link BrokerConfigFlags.supportLevel2Data} configuration flag to `true`.
	 *
	 * @param subscriberUID A string returned by `subscribeDepth`
	 */
	unsubscribeDepth?(subscriberUID: string): void;
	/**
	 * The library calls this function to get the resolution that will be used to calculate the Volume Profile Visible Range indicator.
	 *
	 * Usually you might want to implement this method to calculate the indicator more accurately.
	 * The implementation really depends on how much data you can transfer to the library and the depth of data in your data feed.
	 * **Remark:** If this function is not provided the library uses currentResolution.
	 *
	 * @param currentResolution Resolution of the symbol
	 * @param from Unix timestamp (leftmost visible bar)
	 * @param to Unix timestamp (rightmost visible bar)
	 * @param symbolInfo A Symbol object
	 * @returns A resolution
	 */
	getVolumeProfileResolutionForPeriod?(currentResolution: ResolutionString, from: number, to: number, symbolInfo: LibrarySymbolInfo): ResolutionString;
}
/** Quotes datafeed API */
export interface IDatafeedQuotesApi {
	/**
	 * This function is called when the library needs quote data.
	 * The library assumes that `onDataCallback` is called once when all the requested data is received.
	 * @param  {string[]} symbols - symbol names.
	 * @param  {QuotesCallback} onDataCallback - callback to return the requested data.
	 * @param  {QuotesErrorCallback} onErrorCallback - callback for responding with an error.
	 */
	getQuotes(symbols: string[], onDataCallback: QuotesCallback, onErrorCallback: QuotesErrorCallback): void;
	/* 
	 * 当交易平台希望接收某个符号的实时报价时，会调用此函数。
	 * library 假设你会在每次想要更新报价时调用 `onRealtimeCallback`。
	 * @param  {string[]} symbols - 需要偶尔更新（每分钟一次）的符号列表。这些符号包含在观察列表中，但当前不可见。
	 * @param  {string[]} fastSymbols - 需要频繁更新（至少每10秒一次）的符号列表。
	 * @param  {QuotesCallback} onRealtimeCallback - 用于发送实时报价数据更新的回调函数。
	 * @param  {string} listenerGUID - 监听器的唯一标识符。
	 */
	subscribeQuotes(symbols: string[], fastSymbols: string[], onRealtimeCallback: QuotesCallback, listenerGUID: string): void;
	/**
	 * Trading Platform calls this function when it doesn't want to receive updates for this listener anymore.
	 * `listenerGUID` will be the same object that the Library passed to `subscribeQuotes` before.
	 * @param  {string} listenerGUID - unique identifier of the listener
	 */
	unsubscribeQuotes(listenerGUID: string): void;
}
export interface IExternalDatafeed {
	/**
	 * This call is intended to provide the object filled with the configuration data.
	 * The lib assumes that you will call the callback function and pass your datafeed {@link DatafeedConfiguration} as an argument.
	 *
	 * @param  {OnReadyCallback} callback - callback to return your datafeed configuration ({@link DatafeedConfiguration}) to the library.
	 */
	onReady(callback: OnReadyCallback): void;
}
export interface LibrarySubsessionInfo {
	/**
	 * Description of the subsession.
	 *
	 * @example "Regular Trading Hours"
	 */
	description: string;
	/**
	 * Subsession ID.
	 */
	id: LibrarySessionId;
	/**
	 * Session string. See {@link LibrarySymbolInfo.session}.
	 */
	session: string;
	/**
	 * Session corrections string. See {@link LibrarySymbolInfo.corrections}.
	 */
	"session-correction"?: string;
	/**
	 * Session to display. See {@link LibrarySymbolInfo.session_display}.
	 */
	"session-display"?: string;
}
export interface LibrarySymbolInfo {
	/**
 * 它是在交易所内的一个符号名称，例如 `AAPL` 或 `9988`（香港）。
 * 注意它不应包含交易所名称。
 * 此符号名称对用户可见，并且可以重复。
 *
 * 默认情况下，`name` 用于在 [Datafeed API](https://www.tradingview.com/charting-library-docs/latest/connecting_data/datafeed-api/) 中解析符号。
 * 如果使用了 {@link LibrarySymbolInfo.ticker}，库将使用 ticker 进行 Datafeed API 请求。
 */
	name: string;
	/**
	 * 基础符号数组
	 * 示例：对于 `AAPL*MSFT`，它是 `['NASDAQ:AAPL', 'NASDAQ:MSFT']`
	 */
	base_name?: [
		string
	];
	/**
	 * 它是在您的 [符号学](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Symbology) 中特定符号的唯一标识符。
	 * 如果指定了此属性，其值将用于此符号的所有数据请求。
	 * 如果未显式指定 `ticker`，则将其视为与 {@link LibrarySymbolInfo.name} 相同。
	 * 注意它不应包含交易所名称。
	 */
	ticker?: string;
	/**
	 * 符号的描述。
	 * 将显示在此符号的图表图例中。
	 */
	description: string;
	/**
	 * 符号的长描述
	 *
	 * 可选的较长描述。
	 */
	long_description?: string;
	/**
	 * 仪器类型。
	 * 可能的值：{@link SymbolType}
	 */
	type: string;
	/**
	 * 符号的交易时间。时间应为 {@link LibrarySymbolInfo.timezone} 属性中指定的 **交易所** 时区的时间。更多信息请参阅 [交易时段](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Trading-Sessions) 文章。
	 * @example "1700-0200"
	 */
	session: string;
	/**
	 * 要在 UI 中显示的会话值。如果未指定，则使用 `session`。
	 */
	session_display?: string;
	/**
	 * 包含符号非交易假日的字符串。
	 * 假日日期应为 `YYYYMMDD` 格式。
	 * 这些日期不会在图表上显示。
	 *
	 * 您可以使用 {@link LibrarySymbolInfo.corrections} 指定假日的修正。
	 * @example "20181105,20181107,20181112"
	 */
	session_holidays?: string;
	/**
	 * 符号的修正列表。修正是交易会话与 {@link LibrarySymbolInfo.session} 中设置的默认会话不同的日子。
	 * `corrections` 的值是一个字符串，格式如下：`SESSION:YYYYMMDD`。
	 * 更多信息请参阅 [修正](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Symbology#corrections)。
	 *
	 * 下面的字符串指定了两个交易日的修正：
	 *
	 * - 2018年11月13日。这个交易日分为两个会话。第一个会话从四天前（2018年11月9日）的19:00 开始，到四天前的23:50 结束。第二个会话从10:00 开始，到18:45 结束。
	 * - 2018年11月14日。会话从10:00 开始，到14:00 结束。
	 *
	 * @example "1900F4-2350F4,1000-1845:20181113;1000-1400:20181114"
	 */
	corrections?: string;
	/**
	 * 交易交易所（当前（代理）交易所）。
	 * 名称将显示在此符号的图表图例中。
	 *
	 * @example "NYSE"
	 */
	exchange: string;
	/**
	 * 该符号交易的实际上市交易所的简称。
	 * 名称将显示在此符号的图表图例中。
	 *
	 * @example "NYSE"
	 */
	listed_exchange: string;
	/**
	 * 列出该符号的 **交易所** 时区。时区值应为 OlsonDB 格式。
	 * 请参阅 [时区](https://www.tradingview.com/charting-library-docs/latest/ui_elements/timezones) 以获取支持的时区完整列表。
	 */
	timezone: Timezone;
	/**
	 * 价格刻度上显示标签的格式：
	 *
	 * `price` - 根据 `minmov`、`pricescale`、`minmove2`、`fractional` 和 `variableMinTick` 值格式化十进制或分数数字。更多详细信息请参阅 [价格格式](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Symbology#price-format)。
	 * `volume` - 以千、百万、十亿或万亿格式化十进制数字。
	 */
	format: SeriesFormat;
	/**
	 * 价格的小数位数或分数。
	 *
	 * `pricescale` 的值取决于 [价格格式](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Symbology#price-format)。
	 * 如果您希望以十进制格式显示价格，`pricescale` 应为 `10^n`，其中 `n` 是小数位数。
	 * **示例：** `1`，`10`，`10000000`。
	 *
	 * 如果您希望以分数格式显示价格，`pricescale` 应为 `2^n`。
	 * 此值表示分数的数量。
	 * **示例：** `8`，`16`，`256`。
	 */
	pricescale: number;
	/**
	 * 组成一个刻度的单位数量。
	 * 例如，美国股票以十进制报价，刻度为十进制，可以增减 +/- `.01`。
	 * 因此，刻度增量为 1，`minmov = 1`。但 e-mini S&P 期货合约虽然以十进制报价，但以 `.25` 增量变动，因此刻度增量为 25，`minmov = 25`。
	 * 更多信息请参阅 [价格格式](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Symbology#price-format)。
	 */
	minmov: number;
	/**
	 * 对于常见价格可以省略。
	 *
	 * 分数价格以两种不同形式显示：1) `xx'yy`（例如，`133'21`）2) `xx'yy'zz`（例如，`133'21'5`）。
	 *
	 * - `xx` 是整数部分。
	 * - `minmov/pricescale` 是分数。
	 * - `minmove2` 用于形式 2。
	 * - `fractional` 是 `true`。
	 * - `variableMinTick` 被省略。
	 *
	 * 示例：
	 *
	 * 如果 `minmov = 1`，`pricescale = 128` 且 `minmove2 = 4`：
	 *
	 * - `119'16'0` 表示 `119 + 16/32`
	 * - `119'16'2` 表示 `119 + 16.25/32`
	 * - `119'16'5` 表示 `119 + 16.5/32`
	 * - `119'16'7` 表示 `119 + 16.75/32`
	 *
	 * 更多示例：
	 *
	 * - `ZBM2014 (T-Bond)` 为 `1/32`：`minmov = 1`，`pricescale = 32`，`minmove2 = 0`
	 * - `ZCM2014 (Corn)` 为 `2/8`：`minmov = 2`，`pricescale = 8`，`minmove2 = 0`
	 * - `ZFM2014 (5 year t-note)` 为 `1/4 of 1/32`：`minmov = 1`，`pricescale = 128`，`minmove2 = 4`
	 */
	fractional?: boolean;
	/**
	 * 用于以 [分数的分数](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Symbology#fraction-of-a-fraction-format) 格式显示价格。
	 * 例如，ZBM2023 的刻度大小为 1/4 of 32nd。要显示此证券，设置 `minmov = 1`，`pricescale = 128`，`minmove2 = 4`。
	 *
	 * 对于常见价格，`minmove2` 可以省略或设置为 `0`。
	 */
	minmove2?: number;
	/**
	 * 动态最小价格变动。如果仪器的最小价格变动取决于价格范围，则使用此值。
	 *
	 * 例如，'0.01 10 0.02 25 0.05'，其中价格小于 10 时的刻度大小为 0.01，价格小于 25 时的刻度大小为 0.02，价格大于等于 25 时的刻度大小为 0.05。
	 */
	variable_tick_size?: string;
	/**
	 * 布尔值，指示符号是否包含日内（分钟）历史数据。
	 *
	 * 如果为 `false`，则此特定符号的所有日内分辨率按钮将被禁用。
	 * 如果设置为 `true`，所有直接由数据源提供的日内分辨率必须包含在 `intraday_multipliers` 数组中。
	 *
	 * **警告** 任何日线、周线或月线分辨率不能从日内分辨率推断。
	 *
	 * 如果只有日线、周线和月线，则为 `false`
	 * @default false
	 */
	has_intraday?: boolean;
	/**
	 * 应在此符号的 _分辨率_ 下拉菜单中启用的 [分辨率](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution) 数组。
	 * 数组中的每个项目都应为具有特定 [格式](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution#resolution-format) 的字符串。
	 *
	 * 如果更改符号且新符号不支持选定的分辨率，则分辨率将切换到列表中的第一个可用分辨率。
	 *
	 * **分辨率可用性逻辑（伪代码）：**
	 * ```
	 * resolutionAvailable  =
	 *     resolution.isIntraday
	 *         ? symbol.has_intraday && symbol.supported_resolutions(resolution)
	 *         : symbol.supported_resolutions(resolution);
	 * ```
	 *
	 * 如果 `supported_resolutions` 为 `[]`（空数组），则 _分辨率_ 下拉菜单中的所有分辨率都将被禁用。
	 *
	 * 如果 `supported_resolutions` 为 `undefined`，则启用图表支持的所有分辨率（{@link DatafeedConfiguration.supported_resolutions}）和自定义分辨率。
	 *
	 * 请注意，可用时间框架取决于支持的分辨率。
	 * 需要不可用分辨率的时间框架将被隐藏。
	 * 更多信息请参阅 [时间框架工具栏](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Time-Scale#time-frame-toolbar)。
	 */
	supported_resolutions?: ResolutionString[];
	/**
	 * 数据源直接支持的分辨率（以分钟为单位）数组。每个这样的分辨率都可以传递给并由 `getBars` 实现。默认值为 `[]`，表示数据源支持按任意分钟数聚合。
	 *
	 * 如果数据源仅支持某些分钟分辨率但不支持请求的分辨率，`getBars` 将以较高分辨率作为参数调用（如果需要，可以多次调用），以构建请求的分辨率。
	 *
	 * 例如，如果数据源仅支持分钟分辨率，将 `intraday_multipliers` 设置为 `['1']`。
	 *
	 * 当用户希望查看 5 分钟数据时，`getBars` 将以 1 分钟的分辨率调用，直到库自行构建所有 5 分钟分辨率。
	 * @example (例如："1,5,60") - 只有这些分辨率会被请求，其他分辨率将在可能的情况下使用它们构建
	 * @default []
	 */
	intraday_multipliers?: string[];
	/**
	 * 布尔值，指示符号是否包含秒的历史数据。
	 *
	 * 如果为 `false`，则此特定符号的所有包含秒的分辨率按钮将被禁用。
	 *
	 * 如果设置为 `true`，所有直接由数据源提供的分辨率必须包含在 `seconds_multipliers` 数组中。
	 * @default false
	 */
	has_seconds?: boolean;
	/**
	 * 布尔值，指示符号是否包含刻度的历史数据。
	 *
	 * 如果为 `false`，则此特定符号的所有包含刻度的分辨率按钮将被禁用。
	 * @default false
	 */
	has_ticks?: boolean;
	/**
	 * 包含秒（不包括后缀）的数据源提供的分辨率数组。
	 * 例如，如果数据源支持 `["1S", "5S", "15S"]` 分辨率，但某些符号有 1 秒的 K 线，则应将此符号的 `seconds_multipliers` 设置为 `[1]`。
	 * 这将使库自行构建 5S 和 15S 分辨率。
	 */
	seconds_multipliers?: string[];
	/**
	 * 布尔值，指示此符号的秒 K 线是否可以从刻度构建。仅在交易平台中可用。
	 *
	 * * {@link LibrarySymbolInfo.has_seconds} 必须也为 `true`
	 * * {@link LibrarySymbolInfo.has_ticks} 必须也为 `true`
	 * * {@link LibrarySymbolInfo.seconds_multipliers} 必须为空数组或仅包含数据源自身提供的倍数
	 *
	 * 如果数据源没有秒 K 线或提供的分辨率大于所需分辨率，库将从刻度构建分辨率。例如，数据源提供 `3S` 分辨率。在这种情况下，库只能从刻度构建 `1S` 或 `2S` 分辨率。像 `15S` 这样的分辨率将使用秒 K 线构建。
	 * @default false
	 */
	build_seconds_from_ticks?: boolean;
	/**
	 * 布尔值，指定数据源是否可以提供日线分辨率的历史数据。
	 *
	 * 如果 `has_daily` 设置为 `false`，则此特定符号的所有包含日线的分辨率按钮将被禁用。
	 * 否则，库将从数据源请求日线 K 线。
	 * 数据源提供的所有日线分辨率必须包含在 {@link 图书馆符号信息.daily_multipliers} 数组中。
	 *
	 * @default true
	 */

	has_daily?: boolean;
	/**
 * 包含数据源支持的 [分辨率](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution#resolution-format)（以天为单位 - 不带后缀）的字符串数组。{@link 分辨率字符串}
 *
 * 例如，它可以是类似以下的内容：
 *
 * ```javascript
 * daily_multipliers = ['1', '3', '4', '6', '7'];
 * ```
 * @default ['1']
 */
	daily_multipliers?: string[];
	/**
	 * 布尔值，指示数据源是否有自己的周线和月线分辨率 K 线。
	 *
	 * 如果 `has_weekly_and_monthly` = `false`，则库将使用日线 K 线自行构建相应的分辨率。
	 * 如果不是，则将使用 `weekly_multipliers` 或 `monthly_multipliers`（如果已指定）从数据源请求这些 K 线。
	 * 如果分辨率不在任一列表中，将引发错误。
	 * @default false
	 */
	has_weekly_and_monthly?: boolean;
	/**
	 * 包含数据源支持的 [分辨率](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution#resolution-in-weeks--months)（以周为单位 - 不带后缀）的字符串数组。{@link 分辨率字符串}
	 *
	 * 例如，它可以是类似以下的内容：
	 *
	 * ```javascript
	 * weekly_multipliers = ['1', '5', '10'];
	 * ```
	 * @default ['1']
	 */
	weekly_multipliers?: string[];
	/**
	 * 包含数据源支持的 [分辨率](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution#resolution-in-weeks--months)（以月为单位 - 不带后缀）的字符串数组。{@link 分辨率字符串}
	 *
	 * 例如，它可以是类似以下的内容：
	 *
	 * ```javascript
	 * monthly_multipliers = ['1', '3', '4', '12'];
	 * ```
	 * @default ['1']
	 */
	monthly_multipliers?: string[];
	/**
	 * 布尔值，指示当数据源在此特定时间没有数据时，库是否应在会话中生成空柱。
	 *
	 * 例如，如果您的会话时间为 `0900-1600`，而您的数据在 `11:00` 和 `12:00` 之间有缺失，并且 `has_empty_bars` 为 `true`，那么库将用柱填充这段时间的缺失。
	 *
	 * 如果启用了功能集 `disable_resolution_rebuild`，则不能使用 `has_empty_bars` = `true`。
	 * @default false
	 */
	has_empty_bars?: boolean;
	/**
	 * 表示符号支持的值。可能的值：
	 *
	 * - `ohlcv` — 符号支持开盘价、最高价、最低价、收盘价，并且有成交量。
	 * - `ohlc` — 符号支持开盘价、最高价、最低价、收盘价，但没有成交量。
	 * - `c` — 符号仅支持收盘价。这会使图表仅使用基于线的样式显示符号数据。
	 * @default 'ohlcv'
	 */
	visible_plots_set?: VisiblePlotsSet;
	/**
	 * 整数，表示特定符号的典型成交量值的小数位数。
	 * 0 表示成交量总是整数。
	 * 1 表示小数点后可能有 1 位数字。
	 * @default '0'
	 */
	volume_precision?: number;
	/**
	 * 此符号系列的状态码。
	 * 对于 `delayed_streaming` 和 `endofday` 类型的数据，状态将以图标形式显示，并在 [_图例_](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Legend#display-delayed-data-information) 中的 *数据延迟* 部分显示，位于市场状态图标旁边。
	 * 注意，您还需要启用 [`display_data_mode`](https://www.tradingview.com/charting-library-docs/latest/customization/Featuresets#display_data_mode) 功能集。
	 *
	 * 声明 `delayed_streaming` 时，还必须指定其 {@link LibrarySymbolInfo.delay}（以秒为单位）。
	 */
	data_status?: "streaming" | "endofday" | "delayed_streaming";
	/**
 * 与数据相关联的延迟类型或实时数据的实际延迟。
 * - `0` 表示实时
 * - `-1` 表示日终
 * - 或者以秒为单位的延迟（对于延迟的实时数据）
 */
	delay?: number;
	/**
	 * 布尔值，指示此符号是否为已到期的期货合约。
	 * @default false
	 */
	expired?: boolean;
	/**
	 * 到期日期的 Unix 时间戳。当 `expired` = `true` 时，必须设置此值。
	 * 库将从该时间点开始请求此符号的数据。
	 */
	expiration_date?: number;
	/** 股票在证券信息中显示的行业。 */
	sector?: string;
	/** 股票在证券信息中显示的子行业。 */
	industry?: string;
	/**
	 * 交易工具的交易货币，或者如果启用了货币转换，则为其他货币。
	 * 它显示在证券信息对话框和价格轴上。
	 */
	currency_code?: string;
	/** 交易工具的交易货币。 */
	original_currency_code?: string;
	/**
	 * 交易工具的交易单位的唯一标识符，或者如果启用了单位转换，则为其他标识符。
	 * 它显示在价格轴上。
	 */
	unit_id?: string;
	/**
	 * 交易工具的交易单位的唯一标识符。
	 */
	original_unit_id?: string;
	/**
	 * 允许的单位转换组名称。
	 */
	unit_conversion_types?: string[];
	/**
	 * 在 {@link subsessions} 中指定的子会话的唯一标识符。该值必须与当前在图表上显示的子会话匹配。
	 * 更多信息，请参阅 [扩展会话](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Symbology#extended-sessions) 部分。
	 */
	subsession_id?: string;
	/**
	 * 包含有关扩展会话内某些子会话信息的对象数组。
	 * 更多信息，请参阅 [扩展会话](https://www.tradingview.com/charting-library-docs/latest/connecting_data/Symbology#extended-sessions) 部分。
	 */
	subsessions?: LibrarySubsessionInfo[];
	/**
	 * 符号的价格来源的可选标识符。应与 {@link price_sources} 数组中的一个价格来源匹配。
	 *
	 * 注意，您需要将 [`symbol_info_price_source`](https://www.tradingview.com/charting-library-docs/latest/customization/Featuresets#symbol_info_price_source) 功能集设置为 `true`，以便在主系列图例中显示符号价格来源。
	 */
	price_source_id?: string;
	/**
	 * 符号支持的价格来源。
	 * 价格来源出现在系列图例中，表示符号柱状图值的来源。
	 * 示例价格来源： "现货价格"、"卖价"、"买价" 等。
	 * 查看非 OHLC 系列类型时，价格来源信息非常有价值。
	 *
	 * 注意，您需要将 [`symbol_info_price_source`](https://www.tradingview.com/charting-library-docs/latest/customization/Featuresets#symbol_info_price_source) 功能集设置为 `true`，以便在主系列图例中显示符号价格来源。
	 * @example [{ id: '1', name: '现货价格' }, { id: '321', name: '买价' }]
	 */
	price_sources?: SymbolInfoPriceSource[];
	/**
	 * 作为符号标志显示的图像的 URL。需要启用 `show_symbol_logos` 功能集才能在 UI 中可见。
	 *
	 * - 如果返回单个 URL，则仅使用该 URL 显示符号标志。
	 * - 如果提供两个 URL，则图像将显示为部分重叠的两个圆圈，第一个 URL 的图像在顶部。这通常用于外汇，您希望显示两个国家旗帜作为符号标志。
	 *
	 * 图像最好是正方形。您可以使用浏览器原生支持的任何图像类型。
	 *
	 * 示例：
	 * - `https://yourserver.com/apple.svg`
	 * - `/images/myImage.png`
	 * - `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3...`
	 * - `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4...`
	 */
	logo_urls?: [
		string
	] | [
		string,
		string
	];
	/**
	 * 作为交易所标志显示的图像的 URL。需要启用 `show_exchange_logos` 功能集才能在 UI 中可见。
	 *
	 * 图像最好是正方形。建议使用简单的 SVG 图像。
	 *
	 * 示例：
	 * - `https://yourserver.com/exchangeLogo.svg`
	 * - `/images/myImage.png`
	 * - `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3...`
	 * - `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4...`
	 */
	exchange_logo?: string;
	/**
	 * 包含在符号信息中的附加元数据。
	 * 这些参数不会影响现有的属性（如 'ticker' 或 'name'），也不会被库处理。但是，可以通过 {@link IChartWidgetApi.symbolExt} 方法访问它们，从而影响现有的属性（如 'ticker' 或 'name'）。
	 */
	library_custom_fields?: Record<string, unknown>;
}
export interface Mark {
	/** ID of the mark */
	id: string | number;
	/**
	 * Time for the mark.
	 * Unix timestamp in seconds.
	 */
	time: number;
	/** Color for the mark */
	color: MarkConstColors | MarkCustomColor;
	/** Text content for the mark */
	text: string;
	/** Label for the mark */
	label: string;
	/** Text color for the mark */
	labelFontColor: string;
	/** Minimum size for the mark */
	minSize: number;
	/** Border Width */
	borderWidth?: number;
	/** Border Width when hovering over bar mark */
	hoveredBorderWidth?: number;
	/**
	 * Optional URL for an image to be displayed within the timescale mark.
	 *
	 * The image should ideally be square in dimension. You can use any image type which
	 * the browser supports natively.
	 *
	 * Examples:
	 * - `https://yourserver.com/adobe.svg`
	 * - `/images/myImage.png`
	 * - `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3...`
	 * - `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4...`
	 */
	imageUrl?: string;
	/**
	 * Continue to show text label even when an image has
	 * been loaded for the timescale mark.
	 *
	 * Defaults to `false` if undefined.
	 */
	showLabelWhenImageLoaded?: boolean;
}
export interface MarkCustomColor {
	/** Border color */
	border: string;
	/** Background color */
	background: string;
}
/**
 * Parameters passed to getBars
 */
export interface PeriodParams {
	/**
	 * Unix timestamp (leftmost requested bar)
	 */
	from: number;
	/**
	 * Unix timestamp (rightmost requested bar - not inclusive)
	 */
	to: number;
	/**
	 * The exact amount of bars to load, should be considered a higher priority than `from` if your datafeed supports it
	 */
	countBack: number;
	/**
	 * Used to identify if it's the first call of getBars
	 */
	firstDataRequest: boolean;
}
export interface QuoteDataResponse {
	/** Status code for symbol. Expected values: `ok` | `error` */
	s: "ok" | "error";
	/** Symbol name. This value must be **exactly the same** as in the request */
	n: string;
	/** Quote Values */
	v: unknown;
}
/** Quote Data Error Response */
export interface QuoteErrorData extends QuoteDataResponse {
	/** @inheritDoc */
	s: "error";
	/** @inheritDoc */
	v: object;
}
/** Quote Data Ok Response */
export interface QuoteOkData extends QuoteDataResponse {
	/** @inheritDoc */
	s: "ok";
	/** @inheritDoc */
	v: DatafeedQuoteValues;
}
/**
 * [Symbol Search](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Symbol-Search) result item.
 * Pass the resulting array of symbols as a parameter to {@link SearchSymbolsCallback} of the [`searchSymbols`](https://www.tradingview.com/charting-library-docs/latest/connecting_data/datafeed-api/required-methods#searchsymbols) method.
 *
 * @example
 * ```
 * {
 * 	description: 'Apple Inc.',
 * 	exchange: 'NasdaqNM',
 * 	symbol: 'AAPL',
 * 	ticker: 'AAPL',
 * 	type: 'stock',
 * }
 * ```
 */
export interface SearchSymbolResultItem {
	/** Short symbol name */
	symbol: string;
	/** Description */
	description: string;
	/** Exchange name */
	exchange: string;
	/** Symbol ticker name. Should be an unique id */
	ticker?: string;
	/**
	 * Type of symbol
	 *
	 * 'stock' | 'futures' | 'forex' | 'index'
	 */
	type: string;
	/**
	 * URL of image/s to be displayed as the logo/s for the symbol. The `show_symbol_logos` featureset needs to be enabled for this to be visible in the UI.
	 *
	 * - If a single url is returned then that url will solely be used to display the symbol logo.
	 * - If two urls are provided then the images will be displayed as two partially overlapping
	 * circles with the first url appearing on top. This is typically used for FOREX where you would
	 * like to display two country flags as the symbol logo.
	 *
	 * The image/s should ideally be square in dimension. You can use any image type which
	 * the browser supports natively. Simple SVG images are recommended.
	 *
	 * Examples:
	 * - `https://yourserver.com/symbolName.svg`
	 * - `/images/myImage.png`
	 * - `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3...`
	 * - `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4...`
	 */
	logo_urls?: [
		string
	] | [
		string,
		string
	];
	/**
	 * URL of image to be displayed as the logo for the exchange. The `show_exchange_logos` featureset needs to be enabled for this to be visible in the UI.
	 *
	 * The image should ideally be square in dimension. You can use any image type which
	 * the browser supports natively. Simple SVG images are recommended.
	 *
	 * Examples:
	 * - `https://yourserver.com/exchangeLogo.svg`
	 * - `/images/myImage.png`
	 * - `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3...`
	 * - `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4...`
	 */
	exchange_logo?: string;
}
export interface SymbolInfoPriceSource {
	/** Unique ID */
	id: string;
	/** Short name */
	name: string;
}
/** Additional information about the Symbol's currency or unit */
export interface SymbolResolveExtension {
	/**
	 * Indicates the currency for conversions if `currency_codes` configuration field is set,
	 * and `currency_code` is provided in the original symbol information ({@link LibrarySymbolInfo}).
	 * Read more about [currency conversion](https://www.tradingview.com/charting-library-docs/latest/ui_elements/Price-Scale#currency-conversion).
	 */
	currencyCode?: string;
	/**
	 * Indicates the unit for conversion if `units` configuration
	 * field is set and `unit_id` is provided in the original symbol information ({@link LibrarySymbolInfo}).
	 */
	unitId?: string;
	/**
	 * Trading session type, such as `"regular"` or `"extended"`, that the chart should currently display.
	 */
	session?: string;
}
export interface TimescaleMark {
	/** ID of the timescale mark */
	id: string | number;
	/**
	 * Time for the mark.
	 * Unix timestamp in seconds.
	 */
	time: number;
	/** Color for the timescale mark */
	color: MarkConstColors | string;
	/**
	 * Color for the timescale mark text label.
	 * If undefined then the value provided for `color` will be used.
	 */
	labelFontColor?: MarkConstColors | string;
	/** Label for the timescale mark */
	label: string;
	/** Tooltip content */
	tooltip: string[];
	/** Shape of the timescale mark */
	shape?: TimeScaleMarkShape;
	/**
	 * Optional URL for an image to be displayed within the timescale mark.
	 *
	 * The image should ideally be square in dimension. You can use any image type which
	 * the browser supports natively.
	 *
	 * Examples:
	 * - `https://s3-symbol-logo.tradingview.com/crypto/XTVCBTC.svg`
	 * - `/images/myImage.png`
	 * - `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3...`
	 * - `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAASABIAAD/4...`
	 */
	imageUrl?: string;
	/**
	 * Continue to show text label even when an image has
	 * been loaded for the timescale mark.
	 *
	 * Defaults to `false` if undefined.
	 */
	showLabelWhenImageLoaded?: boolean;
}
export interface Unit {
	/** Unique ID */
	id: string;
	/** Short name */
	name: string;
	/** Description */
	description: string;
}
export type CustomTimezones = "Africa/Cairo" | "Africa/Casablanca" | "Africa/Johannesburg" | "Africa/Lagos" | "Africa/Nairobi" | "Africa/Tunis" | "America/Anchorage" | "America/Argentina/Buenos_Aires" | "America/Bogota" | "America/Caracas" | "America/Chicago" | "America/El_Salvador" | "America/Juneau" | "America/Lima" | "America/Los_Angeles" | "America/Mexico_City" | "America/New_York" | "America/Phoenix" | "America/Santiago" | "America/Sao_Paulo" | "America/Toronto" | "America/Vancouver" | "Asia/Almaty" | "Asia/Ashkhabad" | "Asia/Bahrain" | "Asia/Bangkok" | "Asia/Chongqing" | "Asia/Colombo" | "Asia/Dhaka" | "Asia/Dubai" | "Asia/Ho_Chi_Minh" | "Asia/Hong_Kong" | "Asia/Jakarta" | "Asia/Jerusalem" | "Asia/Karachi" | "Asia/Kathmandu" | "Asia/Kolkata" | "Asia/Kuala_Lumpur" | "Asia/Kuwait" | "Asia/Manila" | "Asia/Muscat" | "Asia/Nicosia" | "Asia/Qatar" | "Asia/Riyadh" | "Asia/Seoul" | "Asia/Shanghai" | "Asia/Singapore" | "Asia/Taipei" | "Asia/Tehran" | "Asia/Tokyo" | "Asia/Yangon" | "Atlantic/Reykjavik" | "Australia/Adelaide" | "Australia/Brisbane" | "Australia/Perth" | "Australia/Sydney" | "Europe/Amsterdam" | "Europe/Athens" | "Europe/Belgrade" | "Europe/Berlin" | "Europe/Bratislava" | "Europe/Brussels" | "Europe/Bucharest" | "Europe/Budapest" | "Europe/Copenhagen" | "Europe/Dublin" | "Europe/Helsinki" | "Europe/Istanbul" | "Europe/Lisbon" | "Europe/London" | "Europe/Luxembourg" | "Europe/Madrid" | "Europe/Malta" | "Europe/Moscow" | "Europe/Oslo" | "Europe/Paris" | "Europe/Prague" | "Europe/Riga" | "Europe/Rome" | "Europe/Stockholm" | "Europe/Tallinn" | "Europe/Vienna" | "Europe/Vilnius" | "Europe/Warsaw" | "Europe/Zurich" | "Pacific/Auckland" | "Pacific/Chatham" | "Pacific/Fakaofo" | "Pacific/Honolulu" | "Pacific/Norfolk" | "US/Mountain";
export type DOMCallback = (data: DOMData) => void;
export type DatafeedErrorCallback = (reason: string) => void;
export type GetMarksCallback<T> = (marks: T[]) => void;
export type HistoryCallback = (bars: Bar[], meta?: HistoryMetadata) => void;
export type LibrarySessionId = "regular" | "extended" | "premarket" | "postmarket";
export type MarkConstColors = "red" | "green" | "blue" | "yellow";
export type OnReadyCallback = (configuration: DatafeedConfiguration) => void;
export type QuoteData = QuoteOkData | QuoteErrorData;
/**
 * Callback to provide Quote data.
 * @param  {QuoteData[]} data - Quote Data
 */
export type QuotesCallback = (data: QuoteData[]) => void;
/**
 * Error callback for quote data request.
 * @param  {QuoteData[]} reason - message describing the reason for the error
 */
export type QuotesErrorCallback = (reason: string) => void;
/**
 * Resolution or time interval is a time period of one bar. Advanced Charts supports tick, intraday (seconds, minutes, hours), and DWM (daily, weekly, monthly) resolutions. The table below describes how to specify different types of resolutions:
 *
 * Resolution | Format | Example
 * ---------|----------|---------
 * Ticks | `xT` | `1T` — one tick, `5T` — five ticks, `100T` — one hundred ticks
 * Seconds | `xS` | `1S` — one second
 * Minutes | `x` | `1` — one minute
 * Hours | `x` minutes | `60` — one hour
 * Days | `xD` | `1D` — one day
 * Weeks | `xW` | `1W` — one week
 * Months | `xM` | `1M` — one month
 * Years | `xM` months | `12M` — one year
 *
 * Refer to [Resolution](https://www.tradingview.com/charting-library-docs/latest/core_concepts/Resolution) for more information.
 */
export type ResolutionString = Nominal<string, "ResolutionString">;
export type ResolveCallback = (symbolInfo: LibrarySymbolInfo) => void;
export type SearchSymbolsCallback = (items: SearchSymbolResultItem[]) => void;
export type SeriesFormat = "price" | "volume";
export type ServerTimeCallback = (serverTime: number) => void;
export type SubscribeBarsCallback = (bar: Bar) => void;
export type TimeScaleMarkShape = "circle" | "earningUp" | "earningDown" | "earning";
export type Timezone = "Etc/UTC" | CustomTimezones;
export type VisiblePlotsSet = "ohlcv" | "ohlc" | "c";

export as namespace TradingView;

export { };
